name: Make Galaxy Z Fold3 5G Recovery

on:
  workflow_dispatch:
    inputs:
      LIBRARY_NAME:
        description: 'Name Library'
        required: true
        default: 'twrp'
      LIBRARY_URL:
        description: 'URL Library'
        required: true
        default: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp'
      LIBRARY_BRANCH:
        description: 'Branch Library'
        required: true
        default: 'twrp-12.1'
      DEVICE_URL:
        description: 'Device URL'
        required: true
        default: 'https://github.com/z02-ahaufun/azkali_twrp_device_samsung_q2q_android14'
      DEVICE_BRANCH:
        description: 'Branch Device'
        required: true
        default: 'main'
      DEVICE_NAME:
        description: 'Device Name'
        required: true
        default: 'q2q'

permissions:
  contents: write

env:
  TZ: America/Santiago

jobs:
  build:
    # if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    
    steps:
    - name: Maximize build disk space
      uses: rokibhasansagar/slimhub_actions@main

    - name: Check Out
      uses: actions/checkout@main

    - name: Prepare the environment
      run: |
        sudo apt clean
        sudo apt update
        sudo apt -y install git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip jq bc ccache libreadline-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev lzop pngcrush rsync schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp bash-completion python openjdk-8-jdk qemu-user-static
      
    - name: Install repo tool
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        export PATH=~/bin:$PATH

    - name: Initialize repo
      run: |
        PATH=~/bin:$PATH
        mkdir workspace
        cd workspace
        echo "::set-output name=pwd::$(pwd)"
        git config --global user.name "bm0x Github Actions bot"
        git config --global user.email "bm0x.actions_bot@github.com"
        repo init --depth=1 -u ${{ github.event.inputs.LIBRARY_URL }} -b ${{ github.event.inputs.LIBRARY_BRANCH }}
        rm -rf .repo/local_manifests
        git clone ${{ github.event.inputs.DEVICE_URL }} -b ${{ github.event.inputs.DEVICE_BRANCH }} .repo/local_manifests
      id: pwd

    - name: Repo sync
      run: |
        PATH=~/bin:$PATH
        cd workspace
        repo sync -j$(nproc --all)

    - name: Build recovery image
      run: |
        PATH=~/bin:$PATH
        cd ${{ steps.pwd.outputs.pwd }}
        export ALLOW_MISSING_DEPENDENCIES=true
        export LC_ALL=C
        source build/envsetup.sh
        lunch twrp_${{ github.event.inputs.DEVICE_NAME }}-eng
        make clean && make clobber
        mka adbd recoveryimage -j$(nproc --all)

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/recovery.img
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/recovery.tar
        name: ${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: Recovery for ${{ github.event.inputs.DEVICE_NAME }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
